models.py
import os
from flask.globals import current_app
from helpers import StandardDAOMixin
from wasd import db


class SavedFile(db.Model, StandardDAOMixin):
    __tablename__ = 'files'

    id = db.Column(db.Integer, primary_key=True)
    hashsum = db.Column(db.String(32), nullable=True, index=True)

    @property
    def fs_unprocessed_name(self):
        filename = str(self.id)
        ext = 'data'
        return os.path.join(current_app.config['UPLOAD_DIR'], '.'.join([filename, ext]))

    @property
    def fs_processed_name(self):
        filename = self.hashsum
        ext = 'data'
        return os.path.join(current_app.config['UPLOAD_DIR'], 'processed', '.'.join([filename, ext]))


class UserFile(db.Model, StandardDAOMixin):
    __tablename__ = 'user_files'

    file_id = db.Column(db.Integer, db.ForeignKey('files.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    original_filename = db.Column(db.String(256))

    file = db.relationship('SavedFile', foreign_keys=[file_id], backref='userfiles')
    user = db.relationship('User', foreign_keys=[user_id], backref='files')

    __table_args__ = (
        db.PrimaryKeyConstraint('file_id', 'user_id', 'original_filename',
                                name='pk__user_files__user_file_name'),
    )

    def delete(self):
        owners_count = len(self.file.userfiles)
        saved_file = self.file
        super().delete()
        if owners_count == 1:
            os.remove(os.path.join(current_app.config['UPLOAD_DIR'],
                                   '.'.join([str(saved_file.id), 'data'])))
            saved_file.delete()

views.py
import mimetypes
import os
from flask import render_template, Blueprint, request, current_app, redirect, url_for, flash, abort
from flask.ext.login import login_required, current_user
from flask.helpers import make_response
from werkzeug.utils import secure_filename

from helpers import DoesNotExists
from models import UserFile, SavedFile

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('base.html')


@main.route('/new/', methods=['POST', 'GET'])
@login_required
def new():
    if current_user.has_exceed_max_files_count():
        flash('Exceed max file count', 'danger')
        return render_template('newfile.html')
    if request.method == 'POST':
        file = request.files['new']
        if file:
            old_file = current_user.get_file(file.filename)
            if old_file:
                old_file.delete()
            new_file = SavedFile()
            new_file.save()
            # _, ext = file.filename.rsplit('.', 1)
            new_filename = str(new_file.id)
            ext = 'data'
            file.save(os.path.join(current_app.config['UPLOAD_DIR'], '.'.join([new_filename, ext])))

            user_file = UserFile()
            user_file.file = new_file
            user_file.user = current_user
            user_file.original_filename = secure_filename(file.filename)
            user_file.save()
            from tasks import calculate_hashsum
            calculate_hashsum.delay(new_file.id)
            return redirect(url_for('main.listall'))
        else:
            flash('No file', 'warning')
    return render_template('newfile.html')


@main.route('/yours/')
@login_required
def listall():
    return render_template('listall.html')


@main.route('/delete/<int:file_id>')
@login_required
def delete(file_id):
    try:
        userfile = UserFile.get(user=current_user, file_id=file_id)
        filename = userfile.original_filename
        userfile.delete()
        flash("File '{}' was successfully deleted!".format(filename), 'success')
    except DoesNotExists:
        flash("No such file or you haven't rights to delete it.", 'warning')
    return redirect(url_for('main.listall'))


@main.route('/download/<userfile>/as/<filename>')
def directlink(userfile, filename):
    try:
        file = SavedFile.get(hashsum=userfile)
        with open(file.fs_processed_name, 'rb') as f:
            resp = make_response(f.read(), 200)
            resp.headers['Content-Type'], resp.headers['Content-Encoding'] = mimetypes.guess_type(filename)
            resp.headers['Content-Disposition'] = 'attachment; filename={}'.format(filename)
            return resp
    except DoesNotExists:
        abort(404)

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}ASD test app{% endblock %}</title>

    {% block styles %}
        {# bootstrap #}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
        {# font-awesome #}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        {% block extrastyles %}{% endblock %}
    {% endblock %}

    {% block scripts %}
        <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
        {# bootstrap #}
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        {% block extrascripts %} {% endblock %}
    {% endblock %}
</head>
<body>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class=flashes>
        {% for category, message in messages %}
            <div class="alert alert-{{ 'info' if category == 'message' else category }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-content">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">WASD</a>
        </div>
        <div id="navbar-content" class="collapse navbar-collapse">
            {% block navitems %}
            <ul class="nav navbar-nav">
            {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('main.new') }}">New</a></li>
                <li><a href="{{ url_for('main.listall') }}">Yours</a></li>
            {% endif %}
            </ul>

            <div class="navbar-right">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated() %}
                    <li class="navbar-text  ">
                        Hello, {{ current_user.get_display_name() }}
                    </li>
                    <li>
                        <a href="{{ url_for('local_auth.logout') }}">Log out</a>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('local_auth.login') }}">Log in</a></li>
                {% endif %}
            </ul>
            </div>
            {% endblock %}
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

templates/listall.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-hover table-stripped">
    <thead>
        <tr>
            <th>Original filename</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for f in current_user.files %}
        <tr>
        <td>{{ f.original_filename }}</td>
        <td>
            {% if f.file.hashsum %}
                <a href="{{ url_for('main.directlink', userfile=f.file.hashsum, filename=f.original_filename) }}"
                   class="btn btn-default" role="button">
                    <i class="fa fa-link"></i> Permalink
                </a>
            {% endif %}
            <a href="{{ url_for('main.delete', file_id=f.file.id) }}" class="btn btn-danger" role="button">
                <i class="fa fa-times"></i> Delete
            </a>
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <form action="." method="post" class="form-horizontal row">
        <div class="form-group">
            <label for="username" class="control-label">Username</label>
            <input type="text" name="username" id="username" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="password" class="control-label">Password</label>
            <input type="password" name="password" id="password" class="form-control"/>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{{ url_for('local_auth.signup') }}" class="btn btn-default" role="button">Sign up</a>
    </form>
    <hr/>
    <div class="row">
        <a href="{{ url_for('linkedin.login', next=url_for('main.index')) }}" class="btn btn-default">
            <i class="fa fa-linkedin"></i>
            Log in with LinkedIn
        </a>
    </div>
</div>
{% endblock %}

templates/newfile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <form action="." method="post" class="form-horizontal" enctype="multipart/form-data">
        <div class="form-group">
            <label for="new">Upload</label>
            <input type="file" name="new"/>
        </div>
        <button class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <form action="." method="post" class="form-inline">
        <label for="email" class="control-label">E-mail</label>
        <input type="text" name="email" id="email" class="form-control"/>
        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
</div>
{% endblock %}